NAME = phonebook

CFLAGS = -Wall -Wextra -Werror -std=c++98 -std=c++98

CPP = c++

SRC = Phonebook.cpp Contacts.cpp utils.cpp main.cpp

HEADER = Phonebook.hpp Contacts.hpp

OBJ=$(SRC:.cpp=.o)

all : $(NAME)

$(NAME) : $(OBJ)
	$(CPP) $(CFLAGS) $(OBJ) -o $(NAME)

%.o : %.cpp $(HEADER)
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@

clean :
	rm -rf $(OBJ)

fclean : clean
	rm -rf $(NAME)

re : fclean all

.PHONY : clean fclean re